---
- name: Join CentOS 7 server to the domain
  include_tasks: ad_join_centos7.yml
  when: ( ansible_distribution == "CentOS" AND ansible_distribution_major_version == "7" )

- name: Join Ubuntu 16 server to the domain
  include_tasks: ad_join_ubuntu16.yml
  when: ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16" )

