---
- hosts: all
  remote_user: ansible
  become: True
  become_user: root
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - setup:
        filter: ansible_service_mgr
  roles:
    - { role: ansible-role-sshdBanners }