---
- name: Reload sshd_config 1
  systemd:
    name: sshd
    state: reloaded
  when: ( ansible_service_mgr == "systemd" )

  name: Reload sshd_config 2
  service:
    name: sshd
    state: reload
  when: ( ansible_service_mgr == "upstart" or "sysvinit" )