---
- name: Systemd sshd reload
  systemd:
    name: sshd
    state: reloaded
  when: ( ansible_service_mgr == "systemd" )

  name: Upstart sshd reload
  service:
    name: sshd
    state: reloaded
  when: ( ansible_service_mgr == "upstart" or "sysvinit" )